name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 discord pytest schema
    - name: Analysing the code with flake8
      run: |
        flake8 --max-line-length 120 $(git ls-files '*.py')
    - name: Run tests with pytest
      run: |
        pytest
    - name: Update release branch
      if: github.ref == 'refs/heads/main'
      run: |
        git fetch origin
        git checkout -b release
        git merge --no-ff origin/${{ github.head_commit.id }}
        git push origin release